# AI-driven Customer Review & Brand Intelligence System

## Pipeline Functionality:

User Query  
      ↓  
(LLM Planner - optional)  
      ↓  
YouTube API Retrieval  
      ↓  
Transcript + Comments Extraction  
      ↓  
NLP Processing (sentiment + embeddings)  
      ↓  
Aggregation (per video + per topic)  
      ↓  
LLM Synthesis (final answer)  
      ↓  
Streamlit UI

###  First install Youtube/Google API Client and test API key:

In [50]:
#!pip install google-api-python-client

In [51]:
# Define User Query
user_query = "DHL Logistik Experiences Erfahrungen"

In [52]:
import re

def make_query_slug(query):

    query = query.lower()

    query = re.sub(r"\s+", "_", query)

    query = re.sub(r"[^a-z0-9_]", "", query)

    return query

query_slug = make_query_slug(user_query)

In [53]:
import json
import os
from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# Load environment variables
load_dotenv()

# Get API key
youtube_api_key = os.getenv("YOUTUBE_API_KEY")

if not youtube_api_key:
    raise ValueError("YOUTUBE_API_KEY not found in environment variables.")

# Build YouTube client
youtube = build(
    "youtube",
    "v3",
    developerKey=youtube_api_key
)

# Define search request for Youtube videos
request = youtube.search().list(
    q=user_query,
    part="snippet",
    type="video",
    maxResults=100
)

response = request.execute()

In [54]:
video_ids = [
    item["id"]["videoId"]
    for item in response["items"]
]

video_details = youtube.videos().list(
    part="snippet,statistics",
    id=",".join(video_ids)
).execute()

In [55]:
# Pretty-print the example response output
print(json.dumps(response, indent=4))

{
    "kind": "youtube#searchListResponse",
    "etag": "35pkSNQv8z1cU9vKgwyLGZ0vZhE",
    "nextPageToken": "CDIQAA",
    "regionCode": "DE",
    "pageInfo": {
        "totalResults": 101701,
        "resultsPerPage": 50
    },
    "items": [
        {
            "kind": "youtube#searchResult",
            "etag": "pT9J_nAfJasYRGvEW6qs-vOCd2E",
            "id": {
                "kind": "youtube#video",
                "videoId": "rYxTuQy-9Dc"
            },
            "snippet": {
                "publishedAt": "2024-08-06T13:13:31Z",
                "channelId": "UCGgxJx2sWzIt07kNivF7JJA",
                "title": "Ein Tag im Leben eines DHL-Paketzustellers: So l\u00e4uft die Zustellung ab!",
                "description": "Hey Freunde, ich war einen Tag Zusteller bei der DHL. Anbei seht ihr einen kleinen Ausschnitt von diesem Tag! Ich war auch ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/rYxTuQy-9Dc/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/rYxTuQy-9Dc/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/rYxTuQy-9Dc/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "Dividente",
                "liveBroadcastContent": "none",
                "publishTime": "2024-08-06T13:13:31Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "OemWuK2f1QhCqUXz2F35dDVEwpg",
            "id": {
                "kind": "youtube#video",
                "videoId": "vhYMeRbvvW4"
            },
            "snippet": {
                "publishedAt": "2020-03-18T15:42:55Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "Werde LEAD Trainee bei Deutsche Post und DHL und starte deine Karriere",
                "description": "Subscribe to our channel: https://www.youtube.com/dhl Find us on: Twitter: https://twitter.com/DeutschePostDHL Facebook: ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/vhYMeRbvvW4/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/vhYMeRbvvW4/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/vhYMeRbvvW4/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2020-03-18T15:42:55Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "MBlI3fr9Hj0l8utdqiAiDXazmD8",
            "id": {
                "kind": "youtube#video",
                "videoId": "suj2NdO56c8"
            },
            "snippet": {
                "publishedAt": "2023-01-22T20:19:01Z",
                "channelId": "UCj089h5WsDdh1q8t54K3ZCw",
                "title": "Inside DHL - Ein ehemaliger Fahrer hat Spannendes zu berichten",
                "description": "\"Der gelbe Sessel\" - wieder LIVE am 17. Februar 2023 um 22 Uhr auf YouTube, Twitch sowie mit Chatfunktion und werbefrei auf ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/suj2NdO56c8/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/suj2NdO56c8/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/suj2NdO56c8/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "Massengeschmack-TV",
                "liveBroadcastContent": "none",
                "publishTime": "2023-01-22T20:19:01Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "YFgwUNBgZsEJZRWC44qUWsbeVR4",
            "id": {
                "kind": "youtube#video",
                "videoId": "Iit4GxfjZkc"
            },
            "snippet": {
                "publishedAt": "2017-08-07T15:00:04Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "DHL Consulting #ProjectExperience - Felix",
                "description": "Project Experience with DHL Consulting - Felix, Senior Consultant, is proud that he designed an employee engagement program ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/Iit4GxfjZkc/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/Iit4GxfjZkc/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/Iit4GxfjZkc/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2017-08-07T15:00:04Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "Ri4TaJb0aiqVkFGfzXMU5d7Djaw",
            "id": {
                "kind": "youtube#video",
                "videoId": "9uBtT_ursbw"
            },
            "snippet": {
                "publishedAt": "2019-03-29T07:26:22Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "AIESEC Program - Laila`s experience at DPDHL Group",
                "description": "Global Talent is a Global Internship Program run by AIESEC, the world's largest youth run organization. Since 1996, DPDHL is ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/9uBtT_ursbw/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/9uBtT_ursbw/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/9uBtT_ursbw/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2019-03-29T07:26:22Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "EK_i9M_Nx4S0_onxSMsk_-_tQ2k",
            "id": {
                "kind": "youtube#video",
                "videoId": "19clwgEmA-0"
            },
            "snippet": {
                "publishedAt": "2018-01-03T19:07:53Z",
                "channelId": "UCw_KcldW7-_2-LuZjEFqrOg",
                "title": "My Internship Experience at DHL",
                "description": "Recorded with https://screencast-o-matic.com.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/19clwgEmA-0/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/19clwgEmA-0/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/19clwgEmA-0/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "Luca Vallavanti",
                "liveBroadcastContent": "none",
                "publishTime": "2018-01-03T19:07:53Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "4WROQBuy5MyKWkFcjDpB1e8fMAM",
            "id": {
                "kind": "youtube#video",
                "videoId": "OrnwnbclXF0"
            },
            "snippet": {
                "publishedAt": "2021-05-11T15:40:45Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "How digitalization is driving customer experience in the logistics sector",
                "description": "Moderator Marianna Evenstein talks with Julia C. Arlinghaus (Fraunhofer Institute for Factory Operation and Automation IFF), ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/OrnwnbclXF0/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/OrnwnbclXF0/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/OrnwnbclXF0/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2021-05-11T15:40:45Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "-IKao0Gr3hfbtNMcVqCcq2EkDuQ",
            "id": {
                "kind": "youtube#video",
                "videoId": "eqq4VqPv-cs"
            },
            "snippet": {
                "publishedAt": "2025-04-03T19:42:32Z",
                "channelId": "UC5wnh6E8S_RrDinYBk6SwHw",
                "title": "Is this DISASTER the FORKLIFT Operators Fault? #forklift #warehouse #worklife",
                "description": "Watch a disaster unfold as this top-shelf pallet comes crashing down! But before you blame the operator, look closer at what ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/eqq4VqPv-cs/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/eqq4VqPv-cs/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/eqq4VqPv-cs/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "Hardhat Highlights",
                "liveBroadcastContent": "none",
                "publishTime": "2025-04-03T19:42:32Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "VmFr2qO0CMZU0JBzw74ut9fy9Ag",
            "id": {
                "kind": "youtube#video",
                "videoId": "QO0w2t1QBuk"
            },
            "snippet": {
                "publishedAt": "2016-11-03T10:47:52Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "DHL, Delft Hyperloop, and the future of logistics: magnetic braking",
                "description": "The Delft Hyperloop team has developed a mode of transportation that can reach speeds of up to 1200 kmh. But how do you slow ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/QO0w2t1QBuk/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/QO0w2t1QBuk/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/QO0w2t1QBuk/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2016-11-03T10:47:52Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "XRmn0WrKenK9IOaHK9r40R8B4jw",
            "id": {
                "kind": "youtube#video",
                "videoId": "PzkQ1T_TOP4"
            },
            "snippet": {
                "publishedAt": "2020-11-26T16:17:22Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "Women at DHL \u2013 Karin Schoombee\u2019s Experience",
                "description": "Let's move things forward. Together. As a global company, DHL values the diversity of their employees as a genuine strength.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/PzkQ1T_TOP4/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/PzkQ1T_TOP4/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/PzkQ1T_TOP4/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2020-11-26T16:17:22Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "HiT5_vdLdRJVbwaKwMWmbHfDniA",
            "id": {
                "kind": "youtube#video",
                "videoId": "RjwsUbO-U7Q"
            },
            "snippet": {
                "publishedAt": "2023-05-21T17:17:22Z",
                "channelId": "UCmn8LWlsrJA7sHNUhVnUO7g",
                "title": "DHL INTERVIEW QUESTIONS AND ANSWERS (How to Pass a DHL Job Interview)",
                "description": "DHL INTERVIEW QUESTIONS AND ANSWERS (How to Pass a DHL Job Interview) By Joshua Brown of: ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/RjwsUbO-U7Q/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/RjwsUbO-U7Q/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/RjwsUbO-U7Q/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "How2Become",
                "liveBroadcastContent": "none",
                "publishTime": "2023-05-21T17:17:22Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "aeB_fpizI0P08ZeMN7HW2_xgYJw",
            "id": {
                "kind": "youtube#video",
                "videoId": "bZvzQ370jrk"
            },
            "snippet": {
                "publishedAt": "2026-03-13T14:36:34Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "Joining DHL as a new starter",
                "description": "What's it really like to join DHL Supply Chain? HR VP Gennene interviews new starter Ellie, who recently joined the business as a ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/bZvzQ370jrk/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/bZvzQ370jrk/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/bZvzQ370jrk/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2026-03-13T14:36:34Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "iyPZDERqhc7OAYbZ7yphSvnS2WU",
            "id": {
                "kind": "youtube#video",
                "videoId": "hb-dB0qVfj0"
            },
            "snippet": {
                "publishedAt": "2025-02-20T13:15:07Z",
                "channelId": "UCfsBLXEWNtr26TM2LLpKbGQ",
                "title": "Did he actually make it?! \ud83c\udfd9\ufe0f",
                "description": "Welcome to New York! Follow our intern Balazs on his journey from Berlin to the Big Apple, where he sees DHL helicopters flying ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/hb-dB0qVfj0/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/hb-dB0qVfj0/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/hb-dB0qVfj0/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    }
                },
                "channelTitle": "DHL",
                "liveBroadcastContent": "none",
                "publishTime": "2025-02-20T13:15:07Z"
            }
        },
        {
            "kind": "youtube#searchResult",
            "etag": "3EzyjOFMTF59khz2xWy4TWS2cwY",
            "id": {
                "kind": "youtube#video",
                "videoId": "2GuwworetsA"
            },
            "snippet": {
                "publishedAt": "2023-06-26T12:45:16Z",
                "channelId": "UC00_xab-ere5qXDhUBOvOsw",
                "title": "DHL Freight Tests Mercedes-Benz E-Truck \u2013 DHL Freight #shorts #sustainability",
                "description": "DHL Freight has made valuable experience on its way to zero-emission transport logistics. Between the DHL Freight Terminal in ...",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/2GuwworetsA/default.jpg",

In [56]:
import pandas as pd

videos = []

for item in video_details["items"]:

    snippet = item.get("snippet", {})
    stats = item.get("statistics", {})

    videos.append({
        "video_id": item.get("id"),

        "title": snippet.get("title"),
        "description": snippet.get("description"),
        "channel": snippet.get("channelTitle"),

        "published_at": snippet.get("publishedAt"),

        "view_count": int(stats.get("viewCount", 0)),
        "like_count": int(stats.get("likeCount", 0)),
        "comment_count": int(stats.get("commentCount", 0)),

        "query_origin": user_query,
        "query_slug": query_slug
    })

videos_df = pd.DataFrame(videos)

videos_df.head(20)

,video_id,title,description,channel,published_at,view_count,like_count,comment_count,query_origin,query_slug
0,rYxTuQy-9Dc,Ein Tag im Leben eines DHL-Paketzustellers: So...,"Hey Freunde,\nich war einen Tag Zusteller bei ...",Dividente,2024-08-06T13:13:31Z,74221,1209,266,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
1,vhYMeRbvvW4,Werde LEAD Trainee bei Deutsche Post und DHL u...,Subscribe to our channel: https://www.youtube....,DHL,2020-03-18T15:42:55Z,7903,57,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
2,suj2NdO56c8,Inside DHL - Ein ehemaliger Fahrer hat Spannen...,"""Der gelbe Sessel"" - wieder LIVE am 17. Februa...",Massengeschmack-TV,2023-01-22T20:19:01Z,16467,527,144,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
3,Iit4GxfjZkc,DHL Consulting #ProjectExperience - Felix,Project Experience with DHL Consulting - Felix...,DHL,2017-08-07T15:00:04Z,1111,10,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
4,9uBtT_ursbw,AIESEC Program - Laila`s experience at DPDHL G...,Global Talent is a Global Internship Program r...,DHL,2019-03-29T07:26:22Z,440,6,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
5,19clwgEmA-0,My Internship Experience at DHL,Recorded with https://screencast-o-matic.com,Luca Vallavanti,2018-01-03T19:07:53Z,1039,22,1,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
6,OrnwnbclXF0,How digitalization is driving customer experie...,Moderator Marianna Evenstein talks with Julia ...,DHL,2021-05-11T15:40:45Z,16843,231,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
7,eqq4VqPv-cs,Is this DISASTER the FORKLIFT Operators Fault?...,Watch a disaster unfold as this top-shelf pall...,Hardhat Highlights,2025-04-03T19:42:32Z,635947,3136,366,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
8,QO0w2t1QBuk,"DHL, Delft Hyperloop, and the future of logist...",The Delft Hyperloop team has developed a mode ...,DHL,2016-11-03T10:47:52Z,58599,30,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
9,PzkQ1T_TOP4,Women at DHL – Karin Schoombee’s Experience,Let’s move things forward. Together.\n\nAs a g...,DHL,2020-11-26T16:17:22Z,748,12,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
10,RjwsUbO-U7Q,DHL INTERVIEW QUESTIONS AND ANSWERS (How to Pa...,DHL INTERVIEW QUESTIONS AND ANSWERS (How to Pa...,How2Become,2023-05-21T17:17:22Z,37001,640,33,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
11,bZvzQ370jrk,Joining DHL as a new starter,What’s it really like to join DHL Supply Chain...,DHL,2026-03-13T14:36:34Z,767,17,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
12,hb-dB0qVfj0,Did he actually make it?! 🏙️,Welcome to New York! Follow our intern Balazs ...,DHL,2025-02-20T13:15:07Z,73863,1119,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
13,2GuwworetsA,DHL Freight Tests Mercedes-Benz E-Truck – DHL ...,DHL Freight has made valuable experience on it...,DHL Freight,2023-06-26T12:45:16Z,3338,23,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
14,zMnw8F2EzFU,Logistics Interview Questions and Answers,"In this video, Faisal Nadeem shared 7 most imp...",Knowledge Topper,2025-02-19T06:39:45Z,540292,3666,101,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
15,kTDGNy5tib4,Amazon 1st day + pre-hire how long will I last,,Mystories,2022-11-18T01:11:01Z,719519,4116,370,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
16,CMwgXcPVAR8,DHL makes augmented reality a standard in logi...,"At DHL, augmented reality is not science ficti...",DHL,2017-08-01T10:25:40Z,35471,154,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
17,xsNIaq-Xf30,DHL Express Central Europe Internship Program,Our Intern Polina Bobyleva is sharing with you...,DHL,2023-07-28T15:49:00Z,1183,22,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
18,vSDhXZg5nU4,Logistics Interview Questions and Answers,"In this video, Faisal Nadeem shared 10 most im...",Knowledge Topper,2025-07-08T06:47:37Z,233612,1394,13,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen
19,5o6-VvA8Gk4,"Experience myDHLFreight, the digital freight p...",Good news for current and future DHL Freight c...,DHL Freight,2023-12-05T23:00:02Z,86,1,0,DHL Logistik Experiences Erfahrungen,dhl_logistik_experiences_erfahrungen

In [57]:
videos_df["published_at"] = pd.to_datetime(videos_df["published_at"])
videos_df["year"] = videos_df["published_at"].dt.year
videos_df["month"] = videos_df["published_at"].dt.month
videos_df["calendar_week"] = videos_df["published_at"].dt.isocalendar().week
videos_df["weekday"] = videos_df["published_at"].dt.day_name()

## Retrieve up to 100 Top Level Comments for each video

In [58]:
all_comments = []

for video_id in video_ids:

    try:

        comments_response = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100
        ).execute()

        for item in comments_response["items"]:

            comment = item["snippet"]["topLevelComment"]["snippet"]

            all_comments.append({
                "comment_id": item["id"],
                "video_id": video_id,

                "author": comment.get("authorDisplayName"),
                "text": comment.get("textOriginal"),
                "like_count": comment.get("likeCount"),
                "published_at": comment.get("publishedAt"),

                "reply_count": item["snippet"].get("totalReplyCount", 0),

                "query_origin": user_query,
                "query_slug": query_slug
            })

    except HttpError as e:

        print(f"Skipping video {video_id}: {e}")

        continue

comments_df = pd.DataFrame(all_comments)

Skipping video vhYMeRbvvW4: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=vhYMeRbvvW4&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video 9uBtT_ursbw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=9uBtT_ursbw&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video OrnwnbclXF0: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=OrnwnbclXF0&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video PzkQ1T_TOP4: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=PzkQ1T_TOP4&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video bZvzQ370jrk: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=bZvzQ370jrk&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video hb-dB0qVfj0: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=hb-dB0qVfj0&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video 2GuwworetsA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=2GuwworetsA&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video CMwgXcPVAR8: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=CMwgXcPVAR8&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video xsNIaq-Xf30: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=xsNIaq-Xf30&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video ylsTByUtWeU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ylsTByUtWeU&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video _kauPlzcwoA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=_kauPlzcwoA&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video DxEdtUTzPtw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=DxEdtUTzPtw&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Skipping video skQ633v8tcY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=skQ633v8tcY&maxResults=100&key=AIzaSyAH0w5BDcRMWOh5D9_vRsYCumD53PYgKcQ&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

In [59]:
comments_df["published_at"] = pd.to_datetime(comments_df["published_at"])
comments_df["year"] = comments_df["published_at"].dt.year
comments_df["month"] = comments_df["published_at"].dt.month
comments_df["calendar_week"] = comments_df["published_at"].dt.isocalendar().week
comments_df["weekday"] = comments_df["published_at"].dt.day_name()

## Save Dataframes in .csv files together with query metadata

In [60]:
from pathlib import Path
from datetime import datetime

raw_path = Path("data/raw") / query_slug

raw_path.mkdir(parents=True, exist_ok=True)

In [61]:
# Define metadata we want to save across the data pipeline:
metadata = {
    "query": user_query,
    "query_slug": query_slug,
    "retrieved_at": datetime.now().isoformat(),

    "max_results": 20
}

# Save metadata:
with open(raw_path / "metadata.json", "w") as f: #"w" means write mode, file is being written
    json.dump(metadata, f, indent=4)

In [62]:
# Save video and comment raw data:
videos_df.to_csv(raw_path / "videos.csv", index=False)
comments_df.to_csv(raw_path / "comments.csv", index=False)

In [70]:
# Later we can merge comments and videos on the common "video_id" key:
comments_df.merge(videos_df, on="video_id", how="left")

,comment_id,video_id,author,text,like_count_x,published_at_x,reply_count,query_origin_x,query_slug_x,year_x,...,published_at_y,view_count,like_count_y,comment_count,query_origin_y,query_slug_y,year_y,month_y,calendar_week_y,weekday_y
0,UgzIiBAk8-wJF1gLmWF4AaABAg,gFnR-Kcia6c,@sheetalmatharu90,I like the fit of these dresses,0,2025-08-01 17:16:55+00:00,0,Zalando review,zalando_review,2025,...,2025-07-23 07:35:32+00:00,14280,61,3,Zalando review,zalando_review,2025,7,30,Wednesday
1,UgzT0osPPqTS1r6rnLt4AaABAg,gFnR-Kcia6c,@parvindersingh-t2j,Nice,1,2025-07-23 07:38:02+00:00,1,Zalando review,zalando_review,2025,...,2025-07-23 07:35:32+00:00,14280,61,3,Zalando review,zalando_review,2025,7,30,Wednesday
2,UgxgSo_Z8WwvFiJ0jE14AaABAg,GdCwMh8YYfA,@Mathildeeee1111,What Are the shoes called??,1,2026-02-17 21:29:17+00:00,0,Zalando review,zalando_review,2026,...,2023-03-22 17:00:15+00:00,29097,336,4,Zalando review,zalando_review,2023,3,12,Wednesday
3,UgxaMLi7RGWISylk_054AaABAg,GdCwMh8YYfA,@JJjemairo,Heb je een kortingscode voor Zalando,0,2025-01-28 19:32:14+00:00,1,Zalando review,zalando_review,2025,...,2023-03-22 17:00:15+00:00,29097,336,4,Zalando review,zalando_review,2023,3,12,Wednesday
4,UgzltKixWpxqt_SE-314AaABAg,GdCwMh8YYfA,@yunamisplon,So cutee❤,2,2024-08-30 21:52:09+00:00,0,Zalando review,zalando_review,2024,...,2023-03-22 17:00:15+00:00,29097,336,4,Zalando review,zalando_review,2023,3,12,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,UgyDbG9Kvvy_glZT5Kx4AaABAg,7cJHLYTn-bw,@katharinajaksch635,Hi,1,2019-02-13 18:07:20+00:00,0,Zalando review,zalando_review,2019,...,2019-02-13 18:00:01+00:00,64437,653,43,Zalando review,zalando_review,2019,2,7,Wednesday
95,UgzAkGL-T0OB0UVHttp4AaABAg,496-xV2gDQM,@lalanorway,Solid kagd sa zalando søs,0,2022-04-11 10:05:28+00:00,1,Zalando review,zalando_review,2022,...,2021-10-23 09:51:28+00:00,2807,14,5,Zalando review,zalando_review,2021,10,42,Saturday
96,Ugz_eydmvhSoDHdKpeV4AaABAg,496-xV2gDQM,@carieb6396,Are you going to open the box or just look at it.,1,2021-10-25 00:50:36+00:00,0,Zalando review,zalando_review,2021,...,2021-10-23 09:51:28+00:00,2807,14,5,Zalando review,zalando_review,2021,10,42,Saturday
97,UgwDSqPm0EWLg3CpVN94AaABAg,496-xV2gDQM,@EMSAPPLEVLOG,Ako pud sis Zolando sa online basta dili nku m...,0,2021-10-24 18:58:41+00:00,0,Zalando review,zalando_review,2021,...,2021-10-23 09:51:28+00:00,2807,14,5,Zalando review,zalando_review,2021,10,42,Saturday
98,UgwpII-gKd5qRSIuoGN4AaABAg,496-xV2gDQM,@kabbilogans166,Watching,0,2021-10-24 13:28:16+00:00,0,Zalando review,zalando_review,2021,...,2021-10-23 09:51:28+00:00,2807,14,5,Zalando review,zalando_review,2021,10,42,Saturday